apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlinstances.database.example.org
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - database.example.org
  resources:
  - mysqlinstances
  - mysqlinstances/status
  - mysqlinstancerequirements
  - mysqlinstancerequirements/status
  verbs:
  - "*"